[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.7.0"
  export=["salesforce_contact_syncup"]
  name = "salesforce_contact_syncup"
  org = "yasithaorg"
  version = "0.1.0"

